### ISSUE TITLE
TypeError: Cannot read property 'includes' of undefined     at /srv/common/paytm/checksum.js:14:25

### ISSUE THREAD

**Issue by harkal18** [Paytm-Payments/Paytm_App_Checksum_Kit_NodeJs#12]
i m trying to generate checksum hash using node.js utility for checksum generation and i m sure earlier it use to work and now suddenly it has stopped working and giving me the following error :

`TypeError: Cannot read property 'includes' of undefined
    at /srv/common/paytm/checksum.js:14:25
    at Array.forEach (<anonymous>)
    at paramsToString (/srv/common/paytm/checksum.js:13:12)
    at Object.genchecksum (/srv/common/paytm/checksum.js:34:14)
    at Object.<anonymous> (/srv/lib/apis/createPaytmCheckSumHash.f.js:37:24)
    at Generator.next (<anonymous>)
    at /srv/lib/apis/createPaytmCheckSumHash.f.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/srv/lib/apis/createPaytmCheckSumHash.f.js:3:12)
    at module.exports.functions.https.onRequest (/srv/lib/apis/createPaytmCheckSumHash.f.js:15:67)`

`createPaytmCheckSumHash.f.js` is my function lying in apis folder as you can see in the error.

**Comment by iMnoorfahad** [comment]
anyone get solution of this

**Comment by arorabhavik1001** [comment]
same issue
