### ISSUE TITLE
Invalid key length

### ISSUE THREAD

**Issue by piyushagwl007** [Paytm-Payments/Paytm_App_Checksum_Kit_NodeJs#7]
I am getting this error while generating the checksum.

`Error: Invalid key length
0|server   |     at new Cipheriv (crypto.js:219:16)
0|server   |     at Object.Cipheriv (crypto.js:217:12)
0|server   |     at Object.encrypt (/home/my/node/app/path/lib/paytm/crypt.js:27:25)
0|server   |     at /home/my/node/app/path/lib/paytm/checksum.js:40:27
0|server   |     at RandomBytes.ondone (/home/my/node/app/path/lib/paytm/crypt.js:66:7)`

**Comment by sumit12kumar** [comment]
The error clearly says "Error: Invalid key length"
You are using an incorrect Merchant key.

Kindly use correct Merchant key provide by Paytm.

**Comment by vajahath** [comment]
this function creates this error when this lib is pulled to our app.
https://github.com/Paytm-Payments/Paytm_App_Checksum_Kit_NodeJs/blame/master/paytm/crypt.js#L81

**Comment by harkal18** [comment]
paytm is shit

**Comment by harkal18** [comment]
and devs are even shittier
