### ISSUE TITLE
crashing in crypto.

### ISSUE THREAD

**Issue by amitkumar3968** [Paytm-Payments/Paytm_App_Checksum_Kit_NodeJs#8]
Hi, Its crashing at--- below error --
Node version -8.12.0

C:\Users\Desktop\Paytm_App_Checksum_Kit_NodeJs-master>node index.js
Server has started
/generate_checksum
{ MID: 'xxxxxxxxxxxxxx',
  ORDER_ID: 'ORDER00001',
  CUST_ID: 'CUST0001',
  INDUSTRY_TYPE_ID: 'xxxxxxxxx',
  CHANNEL_ID: 'WAP',
  TXN_AMOUNT: '1.00',
  WEBSITE: 'xxxxxxxxxxxx',
  CALLBACK_URL: 'https://pguat.paytm.com/paytmchecksum/paytmCallback.jsp',
  EMAIL: 'abc@gmail.com',
  MOBILE_NO: '9999999999' }
crypto.js:219
  this._handle.initiv(cipher, toBuf(key), toBuf(iv));
               ^

Error: Invalid key length
    at new Cipheriv (crypto.js:219:16)
    at Object.createCipheriv (crypto.js:619:10)
    at Object.encrypt (C:\Users\v-amkmr\Desktop\bingquerstatustool\Paytm_App_Checksum_Kit_NodeJs-master\paytm\crypt.js:27:25)
    at C:\Users\v-amkmr\Desktop\bingquerstatustool\Paytm_App_Checksum_Kit_NodeJs-master\paytm\checksum.js:40:27
    at RandomBytes.ondone (C:\Users\v-amkmr\Desktop\bingquerstatustool\Paytm_App_Checksum_Kit_NodeJs-master\paytm\crypt.js:66:7)

C:\Users\Desktop\Paytm_App_Checksum_Kit_NodeJs-master>

**Comment by sumit12kumar** [comment]
The error clearly says "Error: Invalid key length"
You are using an incorrect Merchant key.

Kindly use correct Merchant key provide by Paytm.
